# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  # socket: /path/to/mysql/socket   # Uncomment this line if you are using a socket connection
  host: localhost                 # Change this to your MySQL host if it's not running locally
  port: 3306                      # Change this to your MySQL port if it's not the default
development:
  <<: *default
  database: library_management_dev
test:
  <<: *default
  database: library_management_test
production:
  <<: *default
  database: library_management_prod
